#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_cicd="0.0.1"
  jq -n --arg cicd "$ver_cicd" '{cicd: $cicd}'
}

version "$@"
